name: 友链申请
description: 申请添加友情链接
title: "[友链申请] "
labels: ["友链"]
body:
  - type: markdown
    attributes:
      value: |
        请填写以下信息，审核通过后自动添加到友链。

  - type: input
    id: name
    attributes:
      label: 博客名称
      description: 【必填】你的博客名称
      placeholder: 云途札记
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: 博客地址
      description: 【必填】完整网址，带 https://
      placeholder: https://blog.lzplus.top
    validations:
      required: true

  - type: input
    id: avatar
    attributes:
      label: 头像地址
      description: 【必填】头像图片直链
      placeholder: https://xxx.com/avatar.jpg
    validations:
      required: true

  - type: input
    id: desc
    attributes:
      label: 博客描述
      description: 【必填】一句话介绍你的博客
      placeholder: 行路于云间，落笔作札记
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: 确认事项
      options:
        - label: 我已将本站添加到我的友链中
          required: true
        - label: 我确认以上信息真实有效
          required: true
